#! /bin/bash
# /etc/init.d/p-script
# p-script init.d 

touch /var/lock/p-script
case "$1" in
  start)
        echo "start"
	/etc/p-modules/p-start/null
	;;
  stop)
        echo "stop"
	/etc/p-modules/p-stop/null
	;;
  reload|force-reload)
        echo "reload"
	/etc/p-modules/p-reload/null
	;;
  restart)
        echo "restart"
	/etc/p-modules/p-restart/null
	;;
  status)
        echo "status"
	/usr/bin/p-status
	;;
  *)
	echo "Usage : service p-script status|start|stop|restart|reload "
        exit 1
	;;
esac

exit 0
